### PR TITLE
Upgrade Gradle to 8.5.

### PR DESCRIPTION
**Pull request by netdpb**

### CODE REVIEW

**Review by cpovirk — APPROVED** [review]

**Comment by netdpb** [comment]
Trying to figure out why the build is breaking.

**Comment by netdpb** [comment]
Can't break it locally. Trying to add `--stacktrace` here.

**Comment by netdpb** [comment]
I give up.

**Comment by wmdietl** [comment]
@netdpb The CI failure looks like something goes wrong with annotation-tools.
Maybe these two help: https://github.com/jspecify/checker-framework/pull/40 and https://github.com/jspecify/checker-framework/pull/41
It works for me locally :-)

**Comment by netdpb** [comment]
It works for me locally too, even without those.

Yes, it's an issue with annotation-tools, which also uses an old Gradle. I think we should give up on this until you've finished deforking. Then we will be able to depend on a released version of annotation-tools (and eisop), right?

**Comment by wmdietl** [comment]
eisop doesn't depend on annotation-tools. Merging the two checker-framework PRs should unblock this PR and wouldn't make deforking harder.

**Comment by netdpb** [comment]
Oh cool! I commented on some Gradle and shell bits of the first one.

**Review by cpovirk — APPROVED** [review]

**Pull request merged**
